name: better-auth-nestjs-demo

services:
  postgres:
    image: postgres:latest
    container_name: better-auth-nestjs-demo-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: better_auth-nestjs_demo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
